#!/bin/sh

# Check if the user is running as root.
if [ `id -u` -ne 0 ]
then
    echo You must be root to run the install. 1>&2
    exit 1
fi

# Create install directories if they don't exist.
for DIR in /usr/local /usr/local/bin /usr/local/classes
do
    if [ ! -d "$DIR" ]
    then
    	mkdir "$DIR"
    fi
done

# Install files are relative to the directory this script is in.
MY_DIR=`dirname "$0"`
if [ "$MY_DIR" = "." ]
then
	MY_DIR=`pwd`
fi

# Do the install.
/usr/bin/install -d /usr/local/bin
/usr/bin/install -d /usr/local/share/java
/usr/bin/install "$MY_DIR"/bin/jget /usr/local/bin
/usr/bin/install "$MY_DIR"/classes/JGet.class /usr/local/share/java
