#!/bin/sh

# Script to launch jget-x.x.jar from the command line.

APP=`basename "$0"`
VIRGIN=1.0
JAR=$APP-$VIRGIN.jar 

BIN_DIR=`dirname "$0"`
if [ "$BIN_DIR" = "." ]
then
	BIN_DIR=`pwd`
fi

TOP_DIR=`dirname "$BIN_DIR"`
LIB_DIR="$TOP_DIR"/lib
FOUND=false

# Search for jars in likely places.
for DIR in "$TOP_DIR"/share/java "$LIB_DIR" "$HOME"/git/"$APP"/build/libs
do
	ABS_JAR="$DIR"/"$JAR"
	if [ -f "$ABS_JAR" ]
	then
		FOUND=true
		break
	fi
done

if [ $FOUND = true ]
then
	exec java -jar "$ABS_JAR" "$@"
else
	echo $0: jar file not found: $JAR
fi

